In [1]:
import math
import numpy as np
f=open(r'C:\Users\123\Desktop\Python3\HW6\GRCh38_latest_genomic.fna(2020_04_14)')
seq={}
seq['NC_000006.12']=''
start=False
for line in f:
    if line.startswith('>'):
        name=line.replace('>','').split()[0]
    if name!='NC_000006.12':
        continue
    else:
        if start==False:
            start=True
        else:
            seq[name]+=line.replace('\n','').strip()
            if len(seq[name])>300001:
                break
f.close()

In [2]:
genome=seq['NC_000006.12'][100000:200000].lower()
genome_another=seq['NC_000006.12'][200000:300000].lower()
print(genome_another)

In [3]:
"""order 0"""
acgt_o0={}
for i in range(100000):
    if genome[i:i+1] not in acgt_o0:
        acgt_o0[genome[i:i+1]] = 1
    else:
        acgt_o0[genome[i:i+1]] += 1
total=100000
o0_p=[]
o0_p_log=[]
for i in range(4):
    num=sorted(acgt_o0.items())[i][1]
    o0_p.append(num/total)
    o0_p_log.append(math.log(num/total,2))

order0_result=0
for i in range(4):
    order0_result+=sorted(acgt_o0.items())[i][1]*o0_p_log[i]
    
print(order0_result)

-197688.94757656846


In [4]:
"""order 1"""
acgt_o1={}
for i in range(99999):
    if genome[i:i+2] not in acgt_o1:
        acgt_o1[genome[i:i+2]] = 1
    else:
        acgt_o1[genome[i:i+2]] += 1
        
print(acgt_o1['aa'])
a =list(acgt_o1.keys())[12]
print(a)
print(acgt_o1[a])
# print(atcg_o1.items[0])
# for i in range(16):
#     print(sorted(acgt_o1.items())[i])
# print(sum(acgt_o1.values()))

11197
aa
11197


In [5]:
total=99999
o1_p=[]
o1_p_log=[]
# 機率是條件機率，不是除與全部的次數 Ex: ac出現的機率是 a先出現"後" c出現的機率!!!
# 感覺這邊或許會有更好的寫法，現在是因為排序過後我可以比較容易找到a出現的總次數
for i in range(16):
    num=sorted(acgt_o1.items())[i][1]
    pre_total=sorted(acgt_o0.items())[int(i/4)][1]
    o1_p.append(num/pre_total)
    o1_p_log.append(math.log(num/pre_total,2))

# print(o1_p)
# print(sum(o1_p))

order1_result=0
for i in range(16):
    order1_result+=sorted(acgt_o1.items())[i][1]*o1_p_log[i]
    
# 要把第一個的機率加上
order1_result+=o0_p_log[3]
print(order1_result)

-193212.69566026417


In [6]:
""" 本來冗長的寫法 """
# atcg_o1=np.zeros(16, dtype=int)
# for i in range(99999):      # i=0~999998
#     if (genome[i]+genome[i+1])=='aa': atcg_o1[0]+=1
#     elif genome[i]+genome[i+1]=='at': atcg_o1[1]+=1
#     elif genome[i]+genome[i+1]=='ac': atcg_o1[2]+=1
#     elif genome[i]+genome[i+1]=='ag': atcg_o1[3]+=1
#     elif genome[i]+genome[i+1]=='ta': atcg_o1[4]+=1
#     elif genome[i]+genome[i+1]=='tt': atcg_o1[5]+=1
#     elif genome[i]+genome[i+1]=='tc': atcg_o1[6]+=1
#     elif genome[i]+genome[i+1]=='tg': atcg_o1[7]+=1
#     elif genome[i]+genome[i+1]=='ca': atcg_o1[8]+=1
#     elif genome[i]+genome[i+1]=='ct': atcg_o1[9]+=1
#     elif genome[i]+genome[i+1]=='cc': atcg_o1[10]+=1
#     elif genome[i]+genome[i+1]=='cg': atcg_o1[11]+=1
#     elif genome[i]+genome[i+1]=='ga': atcg_o1[12]+=1
#     elif genome[i]+genome[i+1]=='gt': atcg_o1[13]+=1
#     elif genome[i]+genome[i+1]=='gc': atcg_o1[14]+=1
#     elif genome[i]+genome[i+1]=='gg': atcg_o1[15]+=1
# sum=99999
# o1_p=[atcg_o1[0]/sum,atcg_o1[1]/sum,atcg_o1[2]/sum,atcg_o1[3]/sum,atcg_o1[4]/sum,atcg_o1[5]/sum,atcg_o1[6]/sum,atcg_o1[7]/sum,atcg_o1[8]/sum,atcg_o1[9]/sum,atcg_o1[10]/sum,atcg_o1[11]/sum,atcg_o1[12]/sum,atcg_o1[13]/sum,atcg_o1[14]/sum,atcg_o1[15]/sum,]
# o1_p_log=[math.log(o1_p[0], 2),math.log(o1_p[1], 2),math.log(o1_p[2], 2),math.log(o1_p[3], 2),math.log(o1_p[4], 2),math.log(o1_p[5], 2),math.log(o1_p[6], 2),math.log(o1_p[7], 2),math.log(o1_p[8], 2),math.log(o1_p[9], 2),math.log(o1_p[10], 2),math.log(o1_p[11], 2),math.log(o1_p[12], 2),math.log(o1_p[13], 2),math.log(o1_p[14], 2),math.log(o1_p[15], 2)]

# order1_result=0
# for i in range(16):
#     order1_result+=atcg_o1[i]*o1_p_log[i]
    
# # 要把第一個的機率加上
# order1_result+=order0_possibility_log[1]
# print(order1_result)

' 本來冗長的寫法 '

In [7]:
"""order 2"""
acgt_o2={}

for i in range(99998):
    if genome[i:i+3] not in acgt_o2:
        acgt_o2[genome[i:i+3]] = 1
    else:
        acgt_o2[genome[i:i+3]] += 1
        
print(acgt_o2['aaa'])
print(sorted(acgt_o2.items())[0])

# for i in range(64):
#     print(sorted(acgt_o2.items())[i])
# print(sum(acgt_o2.values()))

o2_p=[]
o2_p_log=[]
# 機率是條件機率，不是除與全部的次數 Ex: ac出現的機率是 a先出現"後" c出現的機率!!!
# 感覺這邊或許會有更好的寫法
for i in range(64):
    num=sorted(acgt_o2.items())[i][1]
    pre_total=sorted(acgt_o1.items())[int(i/4)][1]
    o2_p.append(num/pre_total)
    o2_p_log.append(math.log(num/pre_total,2))

order2_result=0
for i in range(64):
    order2_result+=sorted(acgt_o2.items())[i][1]*o2_p_log[i]
    
# 要把第一個的機率加上
order2_result+=o0_p_log[3]+o1_p_log[15]
print(order2_result)

4651
('aaa', 4651)
-192099.86954829996


In [8]:
from hmmlearn import hmm
states = ["box 1", "box 2", "box3"]
n_states = len(states)

observations = ["red", "white","yellow"]
n_observations = len(observations)

start_probability = np.array([0.2, 0.4, 0.4])

transition_probability = np.array([
  [0.5, 0.2, 0.3],
  [0.3, 0.5, 0.2],
  [0.2, 0.3, 0.5]
])

emission_probability = np.array([
  [0.5, 0.2, 0.3],
  [0.4, 0.3, 0.3],
  [0.7, 0.1, 0.2]
])

model = hmm.MultinomialHMM(n_components=n_states)
model.startprob_=start_probability
model.transmat_=transition_probability
model.emissionprob_=emission_probability

se = np.array([[0, 1, 2, 0, 1]]).T
logprob, box_index = model.decode(se, algorithm='viterbi')
print("颜色:", end="")
print(" ".join(map(lambda t: observations[t], [0, 1, 2, 0, 1])))
print("盒子:", end="")
print(" ".join(map(lambda t: states[t], box_index)))
print("概率值:", end="")
print(np.exp(logprob)) # 这个是因为在hmmlearn底层将概率进行了对数化，防止出现乘积为0的情况

颜色:red white yellow red white
盒子:box3 box 2 box 2 box 2 box 2
概率值:0.0001133999999999999


In [9]:
S1=[]
for i in range(100000):
    if genome[i]=='a': S1.append(0)
    elif genome[i]=='c': S1.append(1)
    elif genome[i]=='g': S1.append(2)
    elif genome[i]=='t': S1.append(3)
S=np.array(S1).reshape((-1,1))

S2=[]
for i in range(100000):
    if genome_another[i]=='a': S2.append(0)
    elif genome_another[i]=='c': S2.append(1)
    elif genome_another[i]=='g': S2.append(2)
    elif genome_another[i]=='t': S2.append(3)
        
S2_np=np.array(S2).reshape((-1,1))

In [10]:
states = ['State1', 'State2', 'State3']
obs = ['a', 'c', 'g', 't']
n_states = len(states)
m_obs = len(obs)

model2 = hmm.MultinomialHMM(n_components=n_states, n_iter=20, tol=0.001)

model2.fit(S)
print("输出根据数据训练出来的π")
print(model2.startprob_)
print("输出根据数据训练出来的A")
print(model2.transmat_)
print("输出根据数据训练出来的B")
print(model2.emissionprob_)

输出根据数据训练出来的π
[3.33863046e-01 4.98749079e-15 6.66136954e-01]
输出根据数据训练出来的A
[[0.34895268 0.28388543 0.3671619 ]
 [0.26999823 0.46615045 0.26385132]
 [0.32759831 0.30149305 0.37090863]]
输出根据数据训练出来的B
[[0.29224022 0.08001682 0.25898202 0.36876093]
 [0.43314887 0.36881292 0.12154532 0.07649288]
 [0.210824   0.15744894 0.25196575 0.37976132]]


In [11]:
logprob, box_index = model2.decode(S, algorithm='viterbi')
print("概率值:", end="")
print(logprob) # 这个是因为在hmmlearn底层将概率进行了对数化，防止出现乘积为0的情况

概率值:-205007.7861578334


In [12]:
print("S:", end="")
print(" ".join(map(lambda t: obs[t], S1)))

In [13]:
print("State:", end="")
print(" ".join(map(lambda t: states[t], box_index)))

In [14]:
logprob2, box_index2 = model2.decode(S2_np, algorithm='viterbi')
print("概率值:", end="")
print(logprob2) # 这个是因为在hmmlearn底层将概率进行了对数化，防止出现乘积为0的情况

概率值:-206826.19358330723
